// <auto-generated />
using System;
using BankApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BankApp.Models.KundDataModel", b =>
                {
                    b.Property<Guid>("KundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Efternamn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Förnamn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lösenord")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Personnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tele")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KundId");

                    b.ToTable("Kunder");

                    b.HasData(
                        new
                        {
                            KundId = new Guid("302df48f-cc0d-40f7-9f1e-37b450a3dd1a"),
                            Adress = "Knasgatan 1",
                            Efternamn = "Knasare",
                            Epost = "knaspelle.knasare@knas.se",
                            Förnamn = "Knaspelle",
                            IsAdmin = false,
                            Lösenord = "knaspass",
                            Personnummer = "1977-04-25",
                            Postnummer = "123 45",
                            Postort = "Knasby",
                            Tele = "070-123 45 67"
                        },
                        new
                        {
                            KundId = new Guid("ab204d34-4754-45a1-9c8e-4915c6bc687d"),
                            Adress = "Ankgatan 1",
                            Efternamn = "Ankare",
                            Epost = "ankpelle.ankare@ank.se",
                            Förnamn = "Ankpelle",
                            IsAdmin = false,
                            Lösenord = "ankpass",
                            Personnummer = "2011-09-11",
                            Postnummer = "543 21",
                            Postort = "Ankby",
                            Tele = "070-765 43 21"
                        },
                        new
                        {
                            KundId = new Guid("504acd8d-1988-4edc-aaed-770fbdb38503"),
                            Adress = "Testgatan 1",
                            Efternamn = "Testare",
                            Epost = "test.testare@test.se",
                            Förnamn = "Test",
                            IsAdmin = false,
                            Lösenord = "pass",
                            Personnummer = "1111-11-11",
                            Postnummer = "111 11",
                            Postort = "Testby",
                            Tele = "111-111 11 11"
                        });
                });

            modelBuilder.Entity("BankApp.Models.SparkontoDataModel", b =>
                {
                    b.Property<Guid>("SparkontoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KundId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.HasKey("SparkontoId");

                    b.HasIndex("KundId")
                        .IsUnique();

                    b.ToTable("Sparkonton");

                    b.HasData(
                        new
                        {
                            SparkontoId = new Guid("6bf3c77f-be64-4203-bfe4-3504661b1f38"),
                            KundId = new Guid("302df48f-cc0d-40f7-9f1e-37b450a3dd1a"),
                            Saldo = 999.00m
                        });
                });

            modelBuilder.Entity("BankApp.Models.SparkontoDataModel", b =>
                {
                    b.HasOne("BankApp.Models.KundDataModel", "Kund")
                        .WithOne("Sparkonto")
                        .HasForeignKey("BankApp.Models.SparkontoDataModel", "KundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kund");
                });

            modelBuilder.Entity("BankApp.Models.KundDataModel", b =>
                {
                    b.Navigation("Sparkonto");
                });
#pragma warning restore 612, 618
        }
    }
}
